### ISSUE TITLE
CS47L63 drivers

### ISSUE THREAD

**Issue by koffes** [CirrusLogic/mcu-drivers#1]
Would it be possible to upload the CS47L63 drivers here as well?

**Comment by alexsven** [comment]
Hi @cirrus-jasonm, I've started to integrate the code from github into our repo now, and it seems cs47l63_syscfg_regs.c/.h is missing from the github-repo. I would expect to find them under cs47l63/config, but can't seem to locate them. I have searched the rest of the repo as well, without any luck. 

By looking at the other chip folders I see that none of them have syscfg_regs files, though they are referencing them in the code. 

Also: Am I correct to assume that cs47l63_fw_img.h needs to be created by using firmware_converter.py?

**Comment by JasJassal** [comment]
Hi Alexander 
The cs47l63_syscfg_regs.c/.h are generated by the makefile (common.mk) using script tools/wisce_script_converter/wisce_script_converter.py, which reads cs47l63/config/wisce_init.txt

The cs47l63_fw_img.h/.c files are generated by the makefile (cs47l63/makefile) using script tools/firmware_converter/firmware_converter.py
By default the firmware_converter tool in the makefile is set to expect a wmfw file that we do not include as part of the public release (see cs47l63\makefile, line 45). 
You will have to obtain a wmfw file. Place this in the cs47l63/fw folder. Then update the makefile to reflect the wmfw filename.

Both the above tools can also be called manually.

Hope this helps,
Jas
jaswinder.jassal@cirrus.com

**Comment by alexsven** [comment]
Thank you for your answer
